version: "3.5"

networks:
  harlem:
    driver: bridge

services:
  microservice:
    build:
      context: src
      dockerfile: microservice/Dockerfile
    hostname: microservice
    depends_on:
      - api
    networks:
      - harlem

  api:
    build:
      context: src
      dockerfile: api/Dockerfile
    ports:
      - "9999:9999"
    hostname: api
    networks:
      - harlem